### ISSUE TITLE
[bug] errors in the total deposit values

### ISSUE THREAD

**Issue by LGSYukiSugiyama** [cosmos-gaminghub/explorer-frontend#61]
## Summary of Bug
The total deposit number in the Proposal List on the Proposal Top Page is shown as 0.000010GAME.
The correct value is 10.000010GAME.
https://nibiru-2000.game-explorer.io/proposals
![Screenshot_20210915-214245932_1_1](https://user-images.githubusercontent.com/89244937/133436012-e92bdca0-a677-4da0-80f4-a95f36555f7d.jpg)

## Version
latest master(6c22bc9)

## Steps to Reproduce
As you can see below, the total deposit number is 10.000010GAME.
```
$ nibirud q gov deposits 1 --chain-id=nibiru-2000
deposits:
- amount:
  - amount: "10000010"
    denom: game
  depositor: nibiru1z9u3cftn89jdqpfm8993r4z7d398auc7tajkgf
  proposal_id: "1"
pagination:
  next_key: null
  total: "0"
```

**Comment by EG-easy** [comment]
Also in the proposal detail page, there are some missing values.

- total GAME should be sum of [yes, no, nowithveto, abstain]
- initial deposit should be 0.000010GAME
- total deposit should be 10.000010GAME

<img width="806" alt="Screenshot 2021-09-16 135148" src="https://user-images.githubusercontent.com/35296935/133551601-fd29b5ab-4974-4044-a697-3b827382fec7.png">
