### ISSUE TITLE
[bug] ubonding tx is not shown in account detail txs

### ISSUE THREAD

**Issue by EG-easy** [cosmos-gaminghub/explorer-frontend#76]
## Summary of Bug
unbonding tx is not shown in account detail txs list.

Here is the unbonding tx
http://nibiru-3000.game-explorer.io/transactions/79FED03863DC04541BB6CF856B47D5D6E2A3EC31F6C54CC8227A8069E2E37C4A

But We can not see it in account detail page.

<img width="794" alt="Screenshot 2022-01-22 174633" src="https://user-images.githubusercontent.com/35296935/150631614-2f7bb6f4-3b90-4194-87bd-ce9ba3d76667.png">

## Steps to Reproduce

____

**Comment by LGSYukiSugiyama** [comment]
Redelegate Tx, Create-Validator Tx and Edit-Validator Tx also seem to be missing.

Account
https://nibiru-3000.game-explorer.io/account/game1vw77nqd3vwu8v56zxujlvase8an6vhe5vpl34h



Create-Validator Tx
https://nibiru-3000.game-explorer.io/transactions/420635DF3EE9816BB4BEB955A96E515CB5F7FE354B6866AD2BBCEA5BC2BD4BFC

Redelegate Tx
https://nibiru-3000.game-explorer.io/transactions/803D3E5EAC225A72917A5D003F6110D1CE1333FFD690632ABB27EE3AF7A0B580

Edit-Validator
https://nibiru-3000.game-explorer.io/transactions/0B87DDD31BDE2D0950268307B11244E55F9AEC3DCEBE4CD30BFC06D04DC3D1FF

![Screenshot from 2022-01-22 22-12-28](https://user-images.githubusercontent.com/89244937/150639940-4beb9077-c311-4ba8-8be7-6717f8b04097.png)

**Comment by LGSYukiSugiyama** [comment]
Other Unjail Tx

Also some Tx Hash
https://nibiru-3000.game-explorer.io/transactions/C7273A89142AB7E651F14849FC75BB8503D712987D926859D7F9F2E1DDAAD449
(I claimed the commission.)

**Comment by EG-easy** [comment]
This is fixed with the backend PR: https://github.com/cosmos-gaminghub/explorer-backend/pull/69
